CREATE TABLE `entrance_keys` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionId` varchar(64) NOT NULL,
	`userAgent` text,
	`language` varchar(16),
	`languages` json,
	`platform` varchar(64),
	`screenWidth` int,
	`screenHeight` int,
	`colorDepth` int,
	`timezone` varchar(64),
	`timezoneOffset` int,
	`referrer` text,
	`connectionType` varchar(32),
	`deviceMemory` float,
	`hardwareConcurrency` int,
	`touchPoints` int,
	`canvasFingerprint` varchar(64),
	`webglRenderer` text,
	`audioFingerprint` varchar(64),
	`fontsDetected` int,
	`cookiesEnabled` int,
	`doNotTrack` varchar(8),
	`entranceFrequency` float,
	`entranceHex` varchar(16),
	`collectionSlot` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `entrance_keys_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sovereign_books` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionId` varchar(64) NOT NULL,
	`userId` int,
	`collectionId` int NOT NULL,
	`bookNumber` int NOT NULL,
	`title` varchar(256) NOT NULL,
	`glyph` varchar(8),
	`entranceFrequency` float,
	`pages` json,
	`qiSyncSeed` int,
	`resonanceScore` float,
	`status` enum('generating','complete','sealed') NOT NULL DEFAULT 'generating',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sovereign_books_id` PRIMARY KEY(`id`)
);
